name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app (Windows)
        run: npm run build:win

      - name: Upload Windows installer to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated release for ${{ github.ref_name }}.
            See commit history for details.
          files: |
            dist/Flashcards Anywhere Setup*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
